image: node:18

pipelines:
  branches:
    main:
      - step:
          name: Verificar e Publicar Vers√µes
          script:
            - echo "Executando script..."
            - npm i -g eitri-cli
            - node check_and_push.js
          services:
            - docker
